### ISSUE TITLE
Multiple inline add buttons

### ISSUE THREAD

**Issue by tobias-reese** [svleeuwen/sortedm2m-filter-horizontal-widget#12]
Is the inclusion of admin/js/inlines.js really neccessary in SortedFilteredSelectMultiple? This leads to multiple inclusion of this file resulting in multiple "Add another" buttons in my inlines.

https://github.com/svleeuwen/sortedm2m-filter-horizontal-widget/blob/d6b609c93d40abc61eff95addec161bd8c748ff1/sortedm2m_filter_horizontal_widget/forms.py#L83

**Comment by chakmear** [comment]
True, this doubles "Add another" buttons for other inlines... I made a work around with a custom widget:

```
class SortedFilteredSelectMultipleCustomJS(SortedFilteredSelectMultiple):
    @property
    def media(self):
        media = forms.Media()
        css = {
            'screen': (STATIC_URL + 'sortedm2m_filter_horizontal_widget/widget.css',)
        }

        js = (STATIC_URL + 'sortedm2m_filter_horizontal_widget/OrderedSelectBox.js',
              STATIC_URL + 'sortedm2m_filter_horizontal_widget/OrderedSelectFilter.js',
              STATIC_URL + 'sortedm2m_filter_horizontal_widget/jquery.min.js',
              # STATIC_URL + 'admin/js/inlines.js'
        )

        media.add_css(css)
        media.add_js(js)
        return media
```

It works very good without importing inlines.js...
