### ISSUE TITLE
popup not closing

### ISSUE THREAD

**Issue by mrdrprofuroboros** [svleeuwen/sortedm2m-filter-horizontal-widget#2]
Using Django 1.9
When I click +add in admin foreign key fields (or M2M key fields) I get the popup window, fill it, click save and it doesn't disappear, staying blank with
popup closing... in the head
it can be closed manually and finally it creates the foreign object, but doesn't link it to the one i was editing

**Comment by PaulGregor** [comment]
same issue :(

**Comment by svleeuwen** [comment]
fixed with latest version
