### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by PaulGregor** [svleeuwen/sortedm2m-filter-horizontal-widget#5]
If I do pull request with fixes, will you update package on https://pypi.python.org ?

**Comment by svleeuwen** [comment]
Yes, for sure.

**Comment by svleeuwen** [comment]
When introducing backwards incompatible changes, please state the minimum django version required. Would be great if we can support 1.8 and up with a single release. Don't know if that's possible though.

**Comment by PaulGregor** [comment]
I have fully working version [sortedm2m-horizontal-widget ](https://pypi.python.org/pypi/sortedm2m-horizontal-widget) . But I've only tested it with Django 1.10. I'll try to make it work for 1.8+ ^_^

**Comment by svleeuwen** [comment]
fixed with latest version
