### ISSUE TITLE
"Select all" and "Clear all" buttons do not work

### ISSUE THREAD

**Issue by sfehlandt** [svleeuwen/sortedm2m-filter-horizontal-widget#9]

**Comment by sfehlandt** [comment]
Fixed here: https://github.com/sfehlandt/sortedm2m-filter-horizontal-widget/commit/77cb0c5433b8432f95eb4db4d232e78159093dc8

**Comment by svleeuwen** [comment]
Thanks for fixing, can you create a pull request?
